version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: adventure-works-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data:/var/lib/mysql-files/seed
      - ./scripts:/scripts
      - ./scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=caching_sha2_password